#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/home-operations/sabnzbd
  # -- image tag
  tag: "4.5"

  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  PUID: 0
  PGID: 0
  # -- Set the container timezone
  TZ: PST
  # HOST_WHITELIST_ENTRIES:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8080

securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 65534 # (Requires CSI support)
  fsGroupChangePolicy: OnRootMismatch # (Requires CSI support)

ingress:
  main:
    # -- Enables or disables the ingress
    enabled: true

    # -- Make this the primary ingress (used in probes, notes, etc...).
    # If there is more than 1 ingress, make sure that only 1 ingress is marked as primary.
    primary: true

    # -- Override the name suffix that is used for this ingress.
    nameOverride:

    # -- Provide additional annotations which may be required.
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
      # kubernetes.io/tls-acme: "true"

    # -- Provide additional labels which may be required.
    labels: {}

    # -- Set the ingressClass that is used for this ingress.
    # Requires Kubernetes >=1.19
    ingressClassName:  # "nginx"

    ## Configure the hosts for the ingress
    hosts:
      -  # -- Host address. Helm template can be passed.
        host: sabnzbd.greaterfaydark.net
        ## Configure the paths for the host
        paths:
          -  # -- Path.  Helm template can be passed.
            path: /
            # -- Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
            service:
              # -- Overrides the service name reference for this path
              name: sabnzbd
              # -- Overrides the service port reference for this path
              port: 8080

    # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
    tls:
     - secretName: sabnzbd-ingress-cert
       hosts:
         - sabnzbd.greaterfaydark.net

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
  downloads:
    enabled: true
    mountPath: /media
    existingClaim: media-pvc
    subPath: Library/media

